name: AVL Set CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Lean ${{ matrix.lean }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        lean: [stable, nightly]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install Elan
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
        
    - name: Setup Lean ${{ matrix.lean }}
      run: |
        elan toolchain install leanprover/lean4:${{ matrix.lean }}
        elan default leanprover/lean4:${{ matrix.lean }}
        
    - name: Version info
      run: |
        echo "Elan: $(elan --version)"
        echo "Lean: $(lean --version)"
        echo "Lake: $(lake --version)"
        
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          .lake
          lake-packages
          ~/.elan
        key: ${{ runner.os }}-lean-${{ matrix.lean }}-${{ hashFiles('lakefile.lean') }}
        restore-keys: |
          ${{ runner.os }}-lean-${{ matrix.lean }}-
          ${{ runner.os }}-lean-
          
    - name: Update dependencies
      run: lake update
      
    - name: Build
      run: lake build
      
    - name: Run tests
      run: |
        echo "Running AVL Set tests..."
        lake exe avlset
        
    - name: Test summary
      if: success()
      run: |
        echo "All tests passed on ${{ matrix.os }} with Lean ${{ matrix.lean }}"
